FROM node:alpine3.16
ENV PORT 3000
ENV PATH /app/node_modules/.bin:$PATH

ENV CHOKIDAR_USEPOLLING true

RUN mkdir /app

WORKDIR /app

EXPOSE 3000
EXPOSE 8000

COPY package* /app/


ENTRYPOINT ["yarn", "start"]
